### ISSUE TITLE
[BUG] Pressing `Frosted Glass Theme: Open CSS` (from menu) leads to an error

### ISSUE THREAD

**Issue by commandblock2** [RichardLuo0/vscode-frosted-glass-theme#19]
**Describe the bug**
I cannot seem to open the file for defining from the menu entry.

**To Reproduce**
1. Start a vscodium with a new profile
2. Install Frosted Glass Theme and [Atom One Dark Theme](https://open-vsx.org/extension/akamud/vscode-theme-onedark)
3. Complete the setup process and run `Frosted Glass Theme: Enable`
4. Restart vscodium and run `Frosted Glass Theme: Open CSS`

**Expected behavior**
It shows the css file.

**Screenshots**
![image](https://github.com/user-attachments/assets/5b6850bc-39fe-4a37-bada-d9a49c64051d)

**Version (please complete the following information):**
 - OS: 
Operating System: Gentoo Linux 2.15
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.6.0
Qt Version: 6.7.3
Kernel Version: 6.11.2-gentoo (64-bit)
Graphics Platform: Wayland

 - VSCode version:
Version: 1.95.3
Release: 24321
Commit: dc5a551c256719475d2d0959270e3836c9bbb632
Date: 2024-11-16T01:21:03.577Z
Electron: 32.2.5
ElectronBuildId: undefined
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Linux x64 6.11.2-gentoo
 - Extension version: v0.8.13

**Logs: **
```log
2024-11-26 00:31:44.963 [error] Error: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")
	at w8 (file:///opt/vscodium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:57019)
	at new Rg (file:///opt/vscodium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:57948)
	at new Yo (file:///opt/vscodium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:59670)
	at Rg.parse (file:///opt/vscodium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:58449)
	at /home/commandblock2/.vscode-oss/extensions/richardluo.frosted-glass-theme-0.8.13-universal/out/extension.js:12:4935
	at J_._executeContributedCommand (file:///opt/vscodium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:39020)
	at J_.$executeContributedCommand (file:///opt/vscodium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:39956)
	at py._doInvokeHandler (file:///opt/vscodium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:122466)
	at py._invokeHandler (file:///opt/vscodium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:122210)
	at py._receiveRequest (file:///opt/vscodium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:120976)
	at py._receiveOneMessage (file:///opt/vscodium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:119802)
	at mh.value (file:///opt/vscodium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:117901)
	at I._deliver (file:///opt/vscodium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:922)
	at I.fire (file:///opt/vscodium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:1242)
	at jn.fire (file:///opt/vscodium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:10940)
	at mh.value (file:///opt/vscodium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:14491)
	at I._deliver (file:///opt/vscodium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:922)
	at I.fire (file:///opt/vscodium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:1242)
	at jn.fire (file:///opt/vscodium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:10940)
	at MessagePortMain.<anonymous> (file:///opt/vscodium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:12702)
	at MessagePortMain.emit (node:events:519:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949) frosted-glass-theme.openCSS {"value":"RichardLuo.frosted-glass-theme","_lower":"richardluo.frosted-glass-theme"}

```
I noticed that before updating vscodium to `app-editors/vscodium-1.95.3.24321-r1` I was using `app-editors/vscodium-1.92.2.24228` and it does not seem to happen on the 1.92 version. Other than opening css/js the extension seems to be working as intended.

**Should you need more info/logs, just tell me what to provide.** It has been a pleasure for me to use this extension. Thank you for your efforts.

**Comment by RichardLuo0** [comment]
Can you try this: https://1drv.ms/u/s!AvQ5Yi4H3cH9h-Uh69angHPdOodseg?e=KZKhhh
And let me know if it works.

**Comment by commandblock2** [comment]
Do you mind pushing the source code for the fix, I am not very sure about installing a unpublished extension, I am willing to try to build the extension myself. Will try this later today :)

**Comment by commandblock2** [comment]
I confirm that this works. 
![image](https://github.com/user-attachments/assets/3628ef08-4646-4313-afa9-dc36525167d2)
