### ISSUE TITLE
[BUG] Error while trying to enable in GNU/Linux with elevated permission

### ISSUE THREAD

**Issue by commandblock2** [RichardLuo0/vscode-frosted-glass-theme#22]
**Describe the bug**
See the uploaded video for the details, enable works when the code belongs to you instead of root, if using root it shows an error.

**To Reproduce**

https://github.com/user-attachments/assets/27ed6aec-e6b2-4faf-bff4-aee0ca3eaa60

**Expected behavior**
Does not show error while enabling.
**Screenshots**

**Version (please complete the following information):**
 - OS: Gentoo (without systemd)
 - VSCode version: 
 ```
 Version: 1.95.3
Release: 24321
Commit: dc5a551c256719475d2d0959270e3836c9bbb632
Date: 2024-11-16T01:21:03.577Z
Electron: 32.2.5
ElectronBuildId: undefined
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Linux x64 6.12.1-gentoo
 ```
 - Extension version: v0.8.14

**Comment by commandblock2** [comment]
here attached is the error message in developer tools
```
Error: Command failed: cd "/home/commandblock2"; export ELECTRON_RUN_AS_NODE="1"; "/usr/bin/pkexec" --disable-internal-agent /bin/bash -c "echo SUDOPROMPT; ELECTRON_RUN_AS_NODE=1  \"/opt/vscodium/codium\" \"/home/commandblock2/.vscode-oss/extensions/richardluo.frosted-glass-theme-0.8.14-universal/out/InjectionAdminMain.js\" --no-sandbox inject \"[{\\\"path\\\":\\\"/home/commandblock2/.vscode-oss/extensions/richardluo.frosted-glass-theme-0.8.14-universal/inject/vscode-frosted-glass-theme.js\\\"}]\" \"/opt/vscodium/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html\""
node:internal/errors:541
      throw error;
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined
    at resolve (node:path:1169:7)
    at new i (/home/commandblock2/.vscode-oss/extensions/richardluo.frosted-glass-theme-0.8.14-universal/out/InjectionAdminMain.js:1:975)
    at /home/commandblock2/.vscode-oss/extensions/richardluo.frosted-glass-theme-0.8.14-universal/out/InjectionAdminMain.js:6:587
    at Array.map (<anonymous>)
    at Object.<anonymous> (/home/commandblock2/.vscode-oss/extensions/richardluo.frosted-glass-theme-0.8.14-universal/out/InjectionAdminMain.js:6:580)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:16955) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.18.0

	at genericNodeError (node:internal/errors:984:15)
	at wrappedFn (node:internal/errors:538:14)
	at ChildProcess.exithandler (node:child_process:422:12)
	at ChildProcess.emit (node:events:519:28)
	at maybeClose (node:internal/child_process:1105:16)
	at Socket.<anonymous> (node:internal/child_process:457:11)
	at Socket.emit (node:events:519:28)
	at Pipe.<anonymous> (node:net:339:12)
```

**Comment by RichardLuo0** [comment]
https://github.com/RichardLuo0/vscode-frosted-glass-theme/actions/runs/12560511885 试下这个

**Comment by commandblock2** [comment]
confirmed to be working as intended.
